version: 0.2
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
    dynamic:
      env:
        compute-type:
          - BUILD_GENERAL1_MEDIUM
        image:
          - public.ecr.aws/q6t8o9m1/cypress-browsers-node14.7.0-chrome84
        variables:
          CY_GROUP_SPEC:
            - "UI - Chrome|chrome|cypress/tests/ui/*"
            - "UI - Chrome - Mobile|chrome|cypress/tests/ui/*|viewportWidth=375,viewportHeight=667"
            - "API|chrome|cypress/tests/api/*"
          WORKERS:
            - 1
            - 2
            - 3
            - 4
            - 5
            - 6
            - 7

phases:
  install:
    commands:
      - echo $CODEBUILD_INITIATOR
      - echo $CY_GROUP_SPEC
      - CY_GROUP=$(echo $CY_GROUP_SPEC | cut -d'|' -f1)
      - CY_BROWSER=$(echo $CY_GROUP_SPEC | cut -d'|' -f2)
      - CY_SPEC=$(echo $CY_GROUP_SPEC | cut -d'|' -f3)
      - CY_CONFIG=$(echo $CY_GROUP_SPEC | cut -d'|' -f4)
      - echo $CY_GROUP
      - echo $CY_BROWSER
      - echo $CY_SPEC
      - echo $CY_CONFIG
      - yarn install --prefer-offline #&> /dev/null
  pre_build:
    commands:
      - yarn run build
  build:
    commands:
      - yarn start:ci:codebuild & npx wait-on http://localhost:3000
      - npx cypress run --record --parallel --browser $CY_BROWSER --ci-build-id $CODEBUILD_INITIATOR --group "$CY_GROUP" --spec "$CY_SPEC" --config "$CY_CONFIG"
cache:
  paths:
    - 'node_modules/**/*'
    - '.cache/**/*'
