version: 0.2
batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
    dynamic:
      env:
        compute-type: 
          - BUILD_GENERAL1_MEDIUM
        image:
          - public.ecr.aws/q6t8o9m1/cypress-browsers-node14.7.0-chrome84
          #- aws/codebuild/windows-base:2019-1.0
        variables:
          NAME:
            - "API Tests"
            - "UI Tests - Chrome"
          SPEC:
            - "cypress/tests/api/*"
            - "cypress/tests/ui/*"
          GROUP:
            - "API"
            - "UI - Chrome"
          #WORKERS:
            #- 1
            #- 2
            #- 3
            #- 4
            #- 5
            #- 6
            #- 7
            #- 8
            #- 9
            #- 10
            #- 11
            #- 12
            #- 13
            #- 14
            #- 15
            #- 16
phases:
  install:
    #runtime-versions:
    #  nodejs: 10
    commands:
      - echo $GROUP
      - yarn install --frozen-lockfile
      - yarn add wait-on
      # Update watched files per https://github.com/facebook/create-react-app/issues/7612#issuecomment-565380404
      - echo fs.inotify.max_user_watches=524288 | tee -a /etc/sysctl.conf && sysctl -p
  pre_build:
    commands:
      - yarn types
      - yarn test:unit:ci
  build:
    commands:
      - yarn start:ci & npx wait-on http://localhost:3000
      - npx cypress run --record --parallel --browser chrome --ci-build-id $CODEBUILD_INITIATOR
cache:
  paths:
    - node_modules/**/*
