version: 0.2

batch:
  fast-fail: false
  build-matrix:
    static:
      ignore-failure: false
      env:
        type: LINUX_CONTAINER
        privileged-mode: true
        compute-type: BUILD_GENERAL1_MEDIUM
    dynamic:
      env:
        compute-type:
          - BUILD_GENERAL1_MEDIUM
        image:
          - public.ecr.aws/cypress-io/cypress/browsers:node14.15.0-chrome86-ff82
        variables:
          CY_GROUP_SPEC:
            - "UI - Chrome|chrome|cypress/tests/ui/*"
            # - "UI - Chrome - Mobile|chrome|cypress/tests/ui/*|viewportWidth=375,viewportHeight=667"
            # - "API|chrome|cypress/tests/api/*"
            # - "UI - Firefox|firefox|cypress/tests/ui/*"
            # - "UI - Firefox - Mobile|firefox|cypress/tests/ui/*|viewportWidth=375,viewportHeight=667"
          WORKERS:
            - 1
            # - 2
            # - 3
            # - 4
            # - 5

phases:
  install:
    commands:
      # - COMMIT_INFO_BRANCH=$(git symbolic-ref HEAD --short 2>/dev/null)
      # - COMMIT_INFO_MESSAGE=$(git log -1 --pretty=%B)
      # - COMMIT_INFO_EMAIL=$(git log -1 --pretty=%ae)
      # - COMMIT_INFO_AUTHOR=$(git log -1 --pretty=%an)
      # - echo $COMMIT_INFO_BRANCH
      # - echo $COMMIT_INFO_MESSAGE
      # - echo $COMMIT_INFO_EMAIL
      # - echo $COMMIT_INFO_AUTHOR
      - echo Installing codebuild-extras...
      - curl -fsSL https://raw.githubusercontent.com/thii/aws-codebuild-extras/fd64ace08a309109058c461e6997807e7473fc61/install >> extras.sh
      - . ./extras.sh
      - echo $CODEBUILD_INITIATOR
      - echo $CY_GROUP_SPEC
      - CY_GROUP=$(echo $CY_GROUP_SPEC | cut -d'|' -f1)
      - CY_BROWSER=$(echo $CY_GROUP_SPEC | cut -d'|' -f2)
      - CY_SPEC=$(echo $CY_GROUP_SPEC | cut -d'|' -f3)
      - CY_CONFIG=$(echo $CY_GROUP_SPEC | cut -d'|' -f4)
      - echo $CY_GROUP
      - echo $CY_BROWSER
      - echo $CY_SPEC
      - echo $CY_CONFIG
      - yarn install --frozen-lockfile
  pre_build:
    commands:
      - yarn build:ci
  build:
    commands:
      - yarn start:ci & npx wait-on http://localhost:3000
      - npx cypress run --record --parallel --browser $CY_BROWSER --ci-build-id $CODEBUILD_INITIATOR --group "$CY_GROUP" --spec "$CY_SPEC" --config "$CY_CONFIG"