version: 0.2
batch:
  fast-fail: true
  build-list:
    - identifier: types_and_unit_tests
      buildspec: buildspec-matrix.yml
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          WORKERS:
            - 1
            - 2
            - 3 
    - identifier: types_and_unit_tests
      buildspec: buildspec-matrix.yml
      env:
        compute-type: BUILD_GENERAL1_MEDIUM
        variables:
          NAME: "API Tests"
          SPEC: "cypress/tests/api/*"
          GROUP: "API"
