version: 0.2

batch:
   fast-fail: true
   build-list:
    - identifier: TypesAndUnit
      buildspec: buildspec-types-unit.yml
    - identifier: API
      buildspec: buildspec-matrix.yml
      env:
        variables:
          NAME: "API Tests"
          SPEC: "cypress/tests/api/*"
          GROUP: "API"
    - identifier: UIChrome
      buildspec: buildspec-matrix.yml
      env:
        variables:
          NAME: "UI Tests - Chrome"
          SPEC: "cypress/tests/ui/*"
          GROUP: "UI - Chrome"
